[package]
name = "app"
version = "0.1.0"
edition = "2021"

[dependencies]
leptos = { workspace = true }
leptos_router = { version = "0.6" }
leptos_meta = { version = "0.6" }

[features]
default = []
hydrate = ["leptos/hydrate", "leptos_meta/hydrate", "leptos_router/hydrate"]
ssr = ["leptos/ssr", "leptos_meta/ssr", "leptos_router/ssr"]
