[workspace]
members = ["louis_blog/app", "louis_blog/server", "louis_blog/front"]
resolver = "2"

[workspace.dependencies]
leptos = { version = "0.7", features = ["nightly", "islands"] }

[profile.release]
codegen-units = 1
lto = true
opt-level = 3

# Defines a size-optimized profile for the WASM bundle in release mode
[profile.wasm-release]
inherits = "release"
opt-level = 'z'
lto = true
codegen-units = 1
panic = "abort"

[[workspace.metadata.leptos]]
name = "louis_blog"
bin-package = "server"
lib-package = "front"
assets-dir = "louis_blog/public"
style-file = "louis_blog/style/main.scss"
site-root = "target/site/louis_blog"
lib-profile-release = "wasm-release"
env = "DEV"
bin-features = ["ssr"]
bin-default-features = false
lib-features = ["hydrate"]
lib-default-features = false
