[workspace]
members = [
    "http_test",
    "louis_blog/app",
    "louis_blog/backend",
    "louis_blog/frontend",
    "louis_blog/wasm_bind",
    "migration",
    "http_test",
]
resolver = "2"

[workspace.dependencies]

[profile.release]
codegen-units = 1
lto = true
opt-level = 3

# Defines a size-optimized profile for the WASM bundle in release mode
[profile.wasm-release]
inherits = "release"
opt-level = 'z'
lto = true
codegen-units = 1
panic = "abort"

[[workspace.metadata.leptos]]
name = "louis_blog"
bin-package = "backend"
lib-package = "frontend"
assets-dir = "louis_blog/public"
style-file = "louis_blog/style/main.scss"
site-root = "target/site"
lib-profile-release = "wasm-release"
env = "DEV"
