[package]
name = "server"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
app = { path = "../app" }
tokio = { version = "1", features = ["rt-multi-thread"], optional = true }
leptos = { workspace = true }
leptos_axum = { version = "0.7", features = [], optional = true }
axum = { version = "0.7", optional = true }

[features]
default = []
ssr = ["dep:axum", "dep:tokio", "dep:leptos_axum", "leptos/ssr"]
